export const ActionTypes = {
    SET_GAME_SETTINGS: "SET_GAME_SETTINGS",
    INCREMENT_ROUND: "INCREMENT_ROUND",
    UPDATE_INSTRUCTIONS: "UPDATE_INSTRUCTIONS",
    FLIP_CARD: "FLIP_CARD",
    SET_PLAYER_SETTINGS: "SET_PLAYER_SETTINGS",
    SET_PLAYER_CARD: "SET_PLAYER_CARD",
    SET_PLAYER_VOTE: "SET_PLAYER_VOTE",
    ADD_PLAYER: "ADD_PLAYER",
    SET_BIN_KEEP_CARDS: "SET_BIN_KEEP_CARDS",
};
